## Microprofile server properties
server.port=8080
server.host=0.0.0.0

tracing.service="todo.backend"
tracing.propagation=w3c

metrics.built-in-meter-name-format=snake
metrics.rest-request-enabled=true
metrics.key-performance-indicators.extended=true

telemetry.span.name-includes-method=true

otel.exporter.name=todo.backend
otel.sdk.disabled=false
otel.service.name=todo.backend
otel.traces.exporter=otlp