{
 "title": "Helidon SE Details",
 "description": "Helidon Endpoint Metrics Monitoring",
 "tags": [ "helidon" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Namespace" },
   {
    "name": "app",
    "label": "SE Application",
    "query": {
     "query": "label_values(jvm_uptime_seconds{namespace=~\"${Namespace:.*}\"},app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "SE Application Details for ${app}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Total SE JVM's",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (instance) (jvm_uptime_seconds{namespace=~\"${Namespace:.*}\",app=~\"${app}\",mp_app=~\"\"}))"
    }
   ]
  },
  {
   "title": "Total Heap Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memory_usedHeap_bytes{namespace=~\"${Namespace:.*}\",app=~\"${app}\",mp_app=~\"\"})"
    }
   ]
  },
  {
   "title": "Total Heap Used %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memory_usedHeap_bytes{namespace=~\"${Namespace:.*}\",app=~\"${app}\",mp_app=~\"\"}) / sum(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\",app=~\"${app}\",mp_app=~\"\"}) * 100"
    }
   ]
  },
  {
   "title": "Total HTTP Requests Last 1m",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(requests_count_total{namespace=~\"${Namespace:.*}\",app=~\"${app}\",mp_app=~\"\"}) - sum(requests_count_total{namespace=~\"${Namespace:.*}\",app=~\"${app}\",mp_app=~\"\"} offset 1m)"
    }
   ]
  },
  {
   "title": "Total HTTP Requests Last 5m",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(requests_count_total{namespace=~\"${Namespace:.*}\",app=~\"${app}\",mp_app=~\"\"}) - sum(requests_count_total{namespace=~\"${Namespace:.*}\",app=~\"${app}\",mp_app=~\"\"} offset 5m)"
    }
   ]
  },
  {
   "title": "Total HTTP Requests Last 15m",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(requests_count_total{namespace=~\"${Namespace:.*}\",app=~\"${app}\",mp_app=~\"\"}) - sum(requests_count_total{namespace=~\"${Namespace:.*}\",app=~\"${app}\",mp_app=~\"\"} offset 15m) >= 0"
    }
   ]
  },
  {
   "title": "Total Heap Available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\",app=~\"${app}\",mp_app=~\"\"})"
    }
   ]
  },
  {
   "title": "HTTP Rate - 1 min",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(requests_count_total{namespace=~\"${Namespace:.*}\",app=~\"${app}\",mp_app=~\"\"}[1m]))"
    }
   ]
  },
  {
   "title": "HTTP Rate - 5 mins",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(requests_count_total{namespace=~\"${Namespace:.*}\",app=~\"${app}\",mp_app=~\"\"}[5m]))"
    }
   ]
  },
  {
   "title": "HTTP Rate - 15 mins",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(requests_count_total{namespace=~\"${Namespace:.*}\",app=~\"${app}\",mp_app=~\"\"}[15m]))"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "table",
   "description": "Total number of instances running this application",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(thread_count{namespace=~\"${Namespace:.*}\",app=~\"${app}\",mp_app=~\"\"}) by (instance)"
    },
    {
     "expr": "avg(vthreads_scheduler_pool_size{namespace=~\"${Namespace:.*}\",app=~\"${app}\",mp_app=~\"\"}) by (instance)"
    },
    {
     "expr": "avg(vthreads_scheduler_mounted_virtual_thread_count{namespace=~\"${Namespace:.*}\",app=~\"${app}\",mp_app=~\"\"}) by (instance)"
    },
    {
     "expr": "sum(classloader_loadedClasses_count{namespace=~\"${Namespace:.*}\",app=~\"${app}\",mp_app=~\"\"}) by (instance)"
    },
    {
     "expr": "sum(memory_usedHeap_bytes{namespace=~\"${Namespace:.*}\",app=~\"${app}\",mp_app=~\"\"}) by (instance)"
    },
    {
     "expr": "sum(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\",app=~\"${app}\",mp_app=~\"\"}) by (instance)"
    },
    {
     "expr": "sum(memory_usedHeap_bytes{namespace=~\"${Namespace:.*}\",app=~\"${app}\",mp_app=~\"\"}) by (instance) / sum(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\",app=~\"${app}\",mp_app=~\"\"}) by (instance)"
    },
    {
     "expr": "sum(gc_total{namespace=~\"${Namespace:.*}\",app=~\"${app}\",mp_app=~\"\"}) by (instance)"
    },
    {
     "expr": "avg(jvm_uptime_seconds{namespace=~\"${Namespace:.*}\",app=~\"${app}\",mp_app=~\"\"})   by (instance)"
    }
   ]
  },
  {
   "title": "Memory Usage: ${app} - All JVM's",
   "type": "timeseries",
   "description": "Memory usage percentage by SE App.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(memory_usedHeap_bytes{namespace=~\"${Namespace:.*}\",app=~\"${app}\",mp_app=~\"\"})  ",
     "legendFormat": "Total Heap Used"
    },
    {
     "expr": "sum(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\",app=~\"${app}\",mp_app=~\"\"})  ",
     "legendFormat": "Total Heap Available"
    }
   ]
  },
  {
   "title": "HTTP Requests - All JVM's",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "requests_count_total{namespace=~\"${Namespace:.*}\", app=~\"${app}\", mp_app=~\"\"} - requests_count_total{namespace=~\"${Namespace:.*}\", app=~\"${app}\",mp_app=~\"\"} offset $__interval > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}