{
 "title": "Helidon MP Details",
 "description": "Helidon Endpoint Metrics Monitoring",
 "tags": [ "helidon" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Namespace" },
   {
    "name": "mp_app",
    "label": "MP Application",
    "query": {
     "query": "label_values(jvm_uptime_seconds{namespace=~\"${Namespace:.*}\"},mp_app)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({mp_app=\"$mp_app\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "MP Application Details for ${mp_app}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Total MP JVM's",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (instance) (jvm_uptime_seconds{namespace=~\"${Namespace:.*}\",mp_app=~\"${mp_app}\",app=~\"\"}))"
    }
   ]
  },
  {
   "title": "Total Heap Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memory_usedHeap_bytes{namespace=~\"${Namespace:.*}\",mp_app=~\"${mp_app}\",app=~\"\"})"
    }
   ]
  },
  {
   "title": "Total Heap Used %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memory_usedHeap_bytes{namespace=~\"${Namespace:.*}\",mp_app=~\"${mp_app}\",app=~\"\"}) / sum(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\",mp_app=~\"${mp_app}\",app=~\"\"}) * 100"
    }
   ]
  },
  {
   "title": "Total HTTP Requests Last 1m",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(requests_count_total{namespace=~\"${Namespace:.*}\",mp_app=~\"${mp_app}\",app=~\"\"}) - sum(requests_count_total{namespace=~\"${Namespace:.*}\",mp_app=~\"${mp_app}\",app=~\"\"} offset 1m) > 0"
    }
   ]
  },
  {
   "title": "Total HTTP Requests Last 5m",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(requests_count_total{namespace=~\"${Namespace:.*}\",mp_app=~\"${mp_app}\",app=~\"\"}) - sum(requests_count_total{namespace=~\"${Namespace:.*}\",mp_app=~\"${mp_app}\",app=~\"\"} offset 5m) > 0"
    }
   ]
  },
  {
   "title": "Total HTTP Requests Last 15m",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(requests_count_total{namespace=~\"${Namespace:.*}\",mp_app=~\"${mp_app}\",app=~\"\"}) - sum(requests_count_total{namespace=~\"${Namespace:.*}\",mp_app=~\"${mp_app}\",app=~\"\"} offset 15m) > 0"
    }
   ]
  },
  {
   "title": "Total Heap Available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\",mp_app=~\"${mp_app}\",app=~\"\"})"
    }
   ]
  },
  {
   "title": "HTTP Rate - 1 min",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(requests_count_total{namespace=~\"${Namespace:.*}\",mp_app=~\"${mp_app}\",app=~\"\"}[1m]))"
    }
   ]
  },
  {
   "title": "HTTP Rate - 5 mins",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(requests_count_total{namespace=~\"${Namespace:.*}\",mp_app=~\"${mp_app}\",app=~\"\"}[5m]))"
    }
   ]
  },
  {
   "title": "HTTP Rate - 15 mins",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(requests_count_total{namespace=~\"${Namespace:.*}\",mp_app=~\"${mp_app}\",app=~\"\"}[15m]))"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "table",
   "description": "Total number of instances running this application",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(thread_count{namespace=~\"${Namespace:.*}\",mp_app=~\"${mp_app}\",app=~\"\"}) by (instance)"
    },
    {
     "expr": "avg(vthreads_scheduler_pool_size{namespace=~\"${Namespace:.*}\",mp_app=~\"${mp_app}\",app=~\"\"}) by (instance)"
    },
    {
     "expr": "avg(vthreads_scheduler_mounted_virtual_thread_count{namespace=~\"${Namespace:.*}\",mp_app=~\"${mp_app}\",app=~\"\"}) by (instance)"
    },
    {
     "expr": "sum(classloader_loadedClasses_count{namespace=~\"${Namespace:.*}\",mp_app=~\"${mp_app}\",app=~\"\"}) by (instance)"
    },
    {
     "expr": "sum(memory_usedHeap_bytes{namespace=~\"${Namespace:.*}\",mp_app=~\"${mp_app}\",app=~\"\"}) by (instance)"
    },
    {
     "expr": "sum(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\",mp_app=~\"${mp_app}\",app=~\"\"}) by (instance)"
    },
    {
     "expr": "sum(memory_usedHeap_bytes{namespace=~\"${Namespace:.*}\",mp_app=~\"${mp_app}\",app=~\"\"}) by (instance) / sum(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\",mp_app=~\"${mp_app}\",app=~\"\"}) by (instance)"
    },
    {
     "expr": "sum(gc_total{namespace=~\"${Namespace:.*}\",mp_app=~\"${mp_app}\",app=~\"\"}) by (instance)"
    },
    {
     "expr": "sum(jvm_uptime_seconds{namespace=~\"${Namespace:.*}\",mp_app=~\"${mp_app}\",app=~\"\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Memory Usage: ${mp_app} - All JVM's",
   "type": "timeseries",
   "description": "Memory usage percentage by MP App",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(memory_usedHeap_bytes{namespace=~\"${Namespace:.*}\",mp_app=~\"${mp_app}\",app=~\"\"})  ",
     "legendFormat": "Total Heap Used"
    },
    {
     "expr": "sum(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\",mp_app=~\"${mp_app}\",app=~\"\"})  ",
     "legendFormat": "Total Heap Available"
    }
   ]
  },
  {
   "title": "HTTP Requests - All JVM's",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "requests_count_total{namespace=~\"${Namespace:.*}\", mp_app=~\"${mp_app}\",app=~\"\"} - requests_count_total{namespace=~\"${Namespace:.*}\", mp_app=~\"${mp_app}\",app=~\"\"} offset $__interval > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "REST Calls - All JVMs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Total REST Calls all JVM's",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method) (REST_request_seconds_count{mp_app=~\"${mp_app}\",app=~\"\"})",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "REST Requests",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(REST_request_seconds_count{namespace=~\"${Namespace:.*}\",mp_app=~\"${mp_app}\",app=~\"\"}) by (method) > 0"
    },
    {
     "expr": "sum(REST_request_seconds_sum{namespace=~\"${Namespace:.*}\",mp_app=~\"${mp_app}\",app=~\"\"}) by (method) > 0"
    }
   ]
  }
 ]
}