{
 "title": "Helidon Main Dashboard",
 "description": "Helidon Endpoint Metrics Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Namespace" },
   { "name": "TopLimit", "label": "Top N Limit", "query": "1,3,5,10,15" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h2>SE Applications</h2></center>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "<center><h2>MP Applications</h2></center>"
   }
  },
  {
   "title": "Total SE Applications",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (se_app) (jvm_uptime_seconds{namespace=~\"${Namespace:.*}\",se_app!=\"\"}))"
    }
   ]
  },
  {
   "title": "Total Heap Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memory_usedHeap_bytes{namespace=~\"${Namespace:.*}\"})"
    }
   ]
  },
  {
   "title": "Percent Heap Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memory_usedHeap_bytes{namespace=~\"${Namespace:.*}\"}) / sum(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\"}) * 100"
    }
   ]
  },
  {
   "title": "Total MP Applications",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (mp_app) (jvm_uptime_seconds{namespace=~\"${Namespace:.*}\",mp_app!=\"\"}))"
    }
   ]
  },
  {
   "title": "Total Heap Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memory_usedHeap_bytes{namespace=~\"${Namespace:.*}\"})"
    }
   ]
  },
  {
   "title": "Percent Heap Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memory_usedHeap_bytes{namespace=~\"${Namespace:.*}\"}) / sum(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\"}) * 100"
    }
   ]
  },
  {
   "title": "Total Heap Available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\"})"
    }
   ]
  },
  {
   "title": "Total SE JVM's",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (instance) (jvm_uptime_seconds{namespace=~\"${Namespace:.*}\",se_app!=\"\"}))"
    }
   ]
  },
  {
   "title": "Total Heap Available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\"})"
    }
   ]
  },
  {
   "title": "Total MP JVM's",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (instance) (jvm_uptime_seconds{namespace=~\"${Namespace:.*}\", mp_app!=\"\"}))"
    }
   ]
  },
  {
   "title": "Memory Usage By SE App",
   "type": "table",
   "description": "Total heap usage summarized by SE App.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\",mp_app=\"\"}) by (se_app)"
    },
    {
     "expr": "sum(memory_usedHeap_bytes{namespace=~\"${Namespace:.*}\",mp_app=\"\"}) by (se_app)"
    },
    {
     "expr": "sum(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\",mp_app=\"\"}) by (se_app)"
    },
    {
     "expr": "sum(memory_usedHeap_bytes{namespace=~\"${Namespace:.*}\",mp_app=\"\"}) by (se_app) / sum(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\",mp_app=\"\"}) by (se_app)  \n"
    }
   ]
  },
  {
   "title": "Memory Usages By MP App",
   "type": "table",
   "description": "Total heap usage summarized by MP App.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\", se_app=\"\"}) by (mp_app)"
    },
    {
     "expr": "sum(memory_usedHeap_bytes{namespace=~\"${Namespace:.*}\",se_app=\"\"}) by (mp_app)"
    },
    {
     "expr": "sum(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\", se_app=\"\"}) by (mp_app)"
    },
    {
     "expr": "sum(memory_usedHeap_bytes{namespace=~\"${Namespace:.*}\",se_app=\"\"}) by (mp_app) / sum(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\", se_app=\"\"}) by (mp_app)  \n"
    }
   ]
  },
  {
   "title": "Memory Usage % by SE App",
   "type": "timeseries",
   "description": "Memory usage percentage by SE App.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(memory_usedHeap_bytes{namespace=~\"${Namespace:.*}\",mp_app=\"\"}) by (se_app) / sum(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\",mp_app=\"\"}) by (se_app)  \n",
     "legendFormat": "{{se_app}}"
    }
   ]
  },
  {
   "title": "Memory Usage % by MP App",
   "type": "timeseries",
   "description": "Memory usage percentage by MP App.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(memory_usedHeap_bytes{namespace=~\"${Namespace:.*}\",se_app=\"\"}) by (mp_app) / sum(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\",se_app=\"\"}) by (mp_app)  \n",
     "legendFormat": "{{mp_app}}"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"$job\", instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "description": " ",
     "gridPos": { "h": 2, "w": 4, "x": 3, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jvm_uptime_seconds{job=\"$job\", instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "CPUs",
     "type": "stat",
     "description": "Number of CPU processors available to the JVM. This is typically the number of CPU hardware threads.",
     "gridPos": { "h": 2, "w": 3, "x": 7, "y": 35 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cpu_availableProcessors{se_app=\"$se_app\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(requests_count_total{job=\"$job\", instance=\"$instance\"}[5m])",
       "legendFormat": "Requests Per Second"
      }
     ]
    },
    {
     "title": "CPU Load Average",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "cpu_systemLoadAverage{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "CPU load"
      }
     ]
    },
    {
     "title": "Heap Size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "memory_usedHeap_bytes{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "Used Heap"
      },
      {
       "expr": "memory_maxHeap_bytes{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "Max Heap"
      }
     ]
    },
    {
     "title": "Thread Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 10, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "thread_count{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "Thread Count"
      }
     ]
    }
   ]
  }
 ]
}