{
 "title": "Helidon Main Dashboard",
 "description": "Helidon Endpoint Metrics Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Namespace" },
   { "name": "TopLimit", "label": "Top N Limit", "query": "1,3,5,10,15" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h2>SE Applications</h2></center>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "<center><h2>MP Applications</h2></center>"
   }
  },
  {
   "title": "Total SE Applications",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (app) (jvm_uptime_seconds{namespace=~\"${Namespace:.*}\",app!=\"\"}))"
    }
   ]
  },
  {
   "title": "Total Heap Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memory_usedHeap_bytes{namespace=~\"${Namespace:.*}\",app!=\"\"})"
    }
   ]
  },
  {
   "title": "Percent Heap Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memory_usedHeap_bytes{namespace=~\"${Namespace:.*}\",app!=\"\"}) / sum(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\",app!=\"\"}) * 100"
    }
   ]
  },
  {
   "title": "Total MP Applications",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (mp_app) (jvm_uptime_seconds{namespace=~\"${Namespace:.*}\",mp_app!=\"\"}))"
    }
   ]
  },
  {
   "title": "Total Heap Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memory_usedHeap_bytes{namespace=~\"${Namespace:.*}\",mp_app!=\"\"})"
    }
   ]
  },
  {
   "title": "Percent Heap Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memory_usedHeap_bytes{namespace=~\"${Namespace:.*}\",mp_app!=\"\"}) / sum(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\",mp_app!=\"\"}) * 100"
    }
   ]
  },
  {
   "title": "Total Heap Available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\",app!=\"\"})"
    }
   ]
  },
  {
   "title": "Total SE JVM's",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (instance) (jvm_uptime_seconds{namespace=~\"${Namespace:.*}\",app!=\"\"}))"
    }
   ]
  },
  {
   "title": "Total Heap Available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\",mp_app!=\"\"})"
    }
   ]
  },
  {
   "title": "Total MP JVM's",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (instance) (jvm_uptime_seconds{namespace=~\"${Namespace:.*}\", mp_app!=\"\"}))"
    }
   ]
  },
  {
   "title": "Memory Usage By SE App",
   "type": "table",
   "description": "Total heap usage summarized by SE App.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\",app!=\"\"}) by (app)"
    },
    {
     "expr": "sum(memory_usedHeap_bytes{namespace=~\"${Namespace:.*}\",app!=\"\"}) by (app)"
    },
    {
     "expr": "sum(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\",app!=\"\"}) by (app)"
    },
    {
     "expr": "sum(memory_usedHeap_bytes{namespace=~\"${Namespace:.*}\",app!=\"\"}) by (app) / sum(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\",app!=\"\"}) by (app)  \n"
    }
   ]
  },
  {
   "title": "Memory Usages By MP App",
   "type": "table",
   "description": "Total heap usage summarized by MP App.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\", mp_app!=\"\"}) by (mp_app)"
    },
    {
     "expr": "sum(memory_usedHeap_bytes{namespace=~\"${Namespace:.*}\",mp_app!=\"\"}) by (mp_app)"
    },
    {
     "expr": "sum(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\", mp_app!=\"\"}) by (mp_app)"
    },
    {
     "expr": "sum(memory_usedHeap_bytes{namespace=~\"${Namespace:.*}\",mp_app!=\"\"}) by (mp_app) / sum(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\", mp_app!=\"\"}) by (mp_app)  \n"
    }
   ]
  },
  {
   "title": "Memory Usage % by SE App",
   "type": "timeseries",
   "description": "Memory usage percentage by SE App.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(memory_usedHeap_bytes{namespace=~\"${Namespace:.*}\",app!=\"\"}) by (app) / sum(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\",app!=\"\"}) by (app)  \n",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Memory Usage % by MP App",
   "type": "timeseries",
   "description": "Memory usage percentage by MP App.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(memory_usedHeap_bytes{namespace=~\"${Namespace:.*}\",mp_app!=\"\"}) by (mp_app) / sum(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\",mp_app!=\"\"}) by (mp_app)  \n",
     "legendFormat": "{{mp_app}}"
    }
   ]
  }
 ]
}