{
 "title": "Helidon SE Details Dashboard",
 "description": "Helidon Endpoint Metrics Monitoring",
 "tags": [ "helidon" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Namespace" },
   {
    "name": "se_app",
    "label": "SE Application",
    "query": {
     "query": "label_values(jvm_uptime_seconds{namespace=~\"${Namespace:.*}\"},se_app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "SE Application Details for ${se_app}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "instance"
  },
  {
   "title": "Total SE JVM's",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (instance) (jvm_uptime_seconds{namespace=~\"${Namespace:.*}\",se_app=~\"${se_app}\"}))"
    }
   ]
  },
  {
   "title": "Total Heap Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memory_usedHeap_bytes{namespace=~\"${Namespace:.*}\",se_app=~\"${se_app}\"})"
    }
   ]
  },
  {
   "title": "Total Heap Used %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memory_usedHeap_bytes{namespace=~\"${Namespace:.*}\",se_app=~\"${se_app}\"}) / sum(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\",se_app=~\"${se_app}\"}) * 100"
    }
   ]
  },
  {
   "title": "Total HTTP Requests Last 1m",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(requests_count_total{namespace=~\"${Namespace:.*}\",se_app=~\"${se_app}\"}) - sum(requests_count_total{namespace=~\"${Namespace:.*}\",se_app=~\"${se_app}\"} offset 1m)"
    }
   ]
  },
  {
   "title": "Total HTTP Requests Last 5m",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(requests_count_total{namespace=~\"${Namespace:.*}\",se_app=~\"${se_app}\"}) - sum(requests_count_total{namespace=~\"${Namespace:.*}\",se_app=~\"${se_app}\"} offset 5m)"
    }
   ]
  },
  {
   "title": "Total HTTP Requests Last 15m",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(requests_count_total{namespace=~\"${Namespace:.*}\",se_app=~\"${se_app}\"}) - sum(requests_count_total{namespace=~\"${Namespace:.*}\",se_app=~\"${se_app}\"} offset 15m) >= 0"
    }
   ]
  },
  {
   "title": "Total Heap Available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\",se_app=~\"${se_app}\"})"
    }
   ]
  },
  {
   "title": "HTTP Rate - 1 min",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(requests_count_total{namespace=~\"${Namespace:.*}\",se_app=~\"${se_app}\"}[1m]))"
    }
   ]
  },
  {
   "title": "HTTP Rate - 5 mins",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(requests_count_total{namespace=~\"${Namespace:.*}\",se_app=~\"${se_app}\"}[5m]))"
    }
   ]
  },
  {
   "title": "HTTP Rate - 15 mins",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(requests_count_total{namespace=~\"${Namespace:.*}\",se_app=~\"${se_app}\"}[15m]))"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "table",
   "description": "Total number of instances running this application",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(thread_count{namespace=~\"${Namespace:.*}\",se_app=~\"${se_app}\"}) by (instance)"
    },
    {
     "expr": "avg(vthreads_scheduler_pool_size{namespace=~\"${Namespace:.*}\",se_app=~\"${se_app}\"}) by (instance)"
    },
    {
     "expr": "avg(vthreads_scheduler_mounted_virtual_thread_count{namespace=~\"${Namespace:.*}\",se_app=~\"${se_app}\"}) by (instance)"
    },
    {
     "expr": "sum(classloader_loadedClasses_count{namespace=~\"${Namespace:.*}\",se_app=~\"${se_app}\"}) by (instance)"
    },
    {
     "expr": "sum(memory_usedHeap_bytes{namespace=~\"${Namespace:.*}\",se_app=~\"${se_app}\"}) by (instance)"
    },
    {
     "expr": "sum(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\",se_app=~\"${se_app}\"}) by (instance)"
    },
    {
     "expr": "sum(memory_usedHeap_bytes{namespace=~\"${Namespace:.*}\",se_app=~\"${se_app}\"}) by (instance) / sum(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\",se_app=~\"${se_app}\"}) by (instance)"
    },
    {
     "expr": "sum(gc_total{namespace=~\"${Namespace:.*}\",se_app=~\"${se_app}\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Memory Usage: ${se_app} - All JVM's",
   "type": "timeseries",
   "description": "Memory usage percentage by SE App.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(memory_usedHeap_bytes{namespace=~\"${Namespace:.*}\",se_app=~\"${se_app}\"})  ",
     "legendFormat": "Total Heap Used"
    },
    {
     "expr": "sum(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\",se_app=~\"${se_app}\"})  ",
     "legendFormat": "Total Heap Available"
    }
   ]
  },
  {
   "title": "HTTP Requests - All JVM's",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "requests_count_total{namespace=~\"${Namespace:.*}\", se_app=~\"${se_app}\"} - requests_count_total{namespace=~\"${Namespace:.*}\", se_app=~\"${se_app}\"} offset $__interval > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JDK24 Virtual Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total VT Pool Size",
     "type": "stat",
     "description": "Current number of platform threads that the scheduler has started but have not terminated",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(vthreads_scheduler_pool_size{namespace=~\"${Namespace:.*}\",se_app=~\"${se_app}\"})"
      }
     ]
    },
    {
     "title": "Target Parallelism",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 3, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(vthreads_scheduler_parallelism{namespace=~\"${Namespace:.*}\",se_app=~\"${se_app}\"})"
      }
     ]
    },
    {
     "title": "Total VT Pool Used All JVMs",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 6, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": " sum(vthreads_scheduler_pool_size{namespace=~\"${Namespace:.*}\",se_app=~\"${se_app}\"}) / sum(vthreads_scheduler_parallelism{namespace=~\"${Namespace:.*}\",se_app=~\"${se_app}\"})"
      }
     ]
    },
    {
     "title": "Total Mounted VT",
     "type": "stat",
     "description": "Estimate of the number of virtual threads that are currently mounted by the scheduler",
     "gridPos": { "h": 4, "w": 3, "x": 11, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(vthreads_scheduler_mounted_virtual_thread_count{namespace=~\"${Namespace:.*}\",se_app=~\"${se_app}\"})"
      }
     ]
    },
    {
     "title": "Current Virtual Threads Mounted - All JVM's",
     "type": "timeseries",
     "description": "Memory usage percentage by SE App.",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(vthreads_scheduler_mounted_virtual_thread_count{namespace=~\"${Namespace:.*}\",se_app=~\"${se_app}\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total Queued VT",
     "type": "stat",
     "description": "Estimate of the number of virtual threads that are queued to the scheduler to start or continue execution",
     "gridPos": { "h": 4, "w": 3, "x": 11, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(vthreads_scheduler_queued_virtual_thread_count{namespace=~\"${Namespace:.*}\",se_app=~\"${se_app}\"})"
      }
     ]
    }
   ]
  }
 ]
}