{
 "title": "Helidon JVM Details",
 "description": "Helidon Endpoint Metrics Monitoring",
 "tags": [ "helidon" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Namespace" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_uptime_seconds{namespace=~\"${Namespace:.*}\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "JVM and GC Details for ${instance}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Application Type",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (type) (\n  label_replace(\n    label_replace(\n       jvm_uptime_seconds{namespace=~\"${Namespace:.*}\",instance=~\"${instance:raw}\"}, \n      \"type\", \n      \"SE\", \n      \"app\", \n      \".+\"\n    ),\n    \"type\", \n    \"MP\", \n    \"mp_app\", \n    \".+\"\n  )\n)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Total Heap Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memory_usedHeap_bytes{namespace=~\"${Namespace:.*}\",instance=~\"${instance:raw}\"})"
    }
   ]
  },
  {
   "title": "Total Heap Available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\",instance=~\"${instance:raw}\"}) "
    }
   ]
  },
  {
   "title": "Total Heap Used %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memory_usedHeap_bytes{namespace=~\"${Namespace:.*}\",instance=~\"${instance:raw}\"})\n/ sum(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\",instance=~\"${instance:raw}\"}) * 100"
    }
   ]
  },
  {
   "title": "Current Thread Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thread_count{namespace=~\"${Namespace:.*}\",instance=~\"${instance:raw}\"}"
    }
   ]
  },
  {
   "title": "JVM Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_uptime_seconds{namespace=~\"${Namespace:.*}\",instance=~\"${instance:raw}\"}"
    }
   ]
  },
  {
   "title": "Total GC's",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gc_total{namespace=~\"${Namespace:.*}\",instance=~\"${instance:raw}\"}) "
    }
   ]
  },
  {
   "title": "Total GC Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gc_time_seconds{namespace=~\"${Namespace:.*}\",instance=~\"${instance:raw}\"}) "
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(memory_usedHeap_bytes{namespace=~\"${Namespace:.*}\",instance=~\"${instance:raw}\"})  ",
     "legendFormat": "Total Heap Used"
    },
    {
     "expr": "sum(memory_maxHeap_bytes{namespace=~\"${Namespace:.*}\",instance=~\"${instance:raw}\"})  ",
     "legendFormat": "Total Heap Available"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(requests_count_total{namespace=~\"${Namespace:.*}\",instance=~\"${instance:raw}\"}[5m])",
     "legendFormat": "Request Rate"
    }
   ]
  },
  {
   "title": "GC's Over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "gc_total{namespace=~\"${Namespace:.*}\",instance=~\"${instance:raw}\"} - gc_total{namespace=~\"${Namespace:.*}\",instance=~\"${instance:raw}\"} offset $__interval",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Load Average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cpu_systemLoadAverage{namespace=~\"${Namespace:.*}\",instance=~\"${instance:raw}\"}",
     "legendFormat": "Thread Count"
    }
   ]
  },
  { "title": "JDK24+ Virtual Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "VT Pool Size",
   "type": "stat",
   "description": "Current number of platform threads that the scheduler has started but have not terminated",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vthreads_scheduler_pool_size{namespace=~\"${Namespace:.*}\",instance=~\"${instance}\"}) "
    }
   ]
  },
  {
   "title": "Target Parallelism",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vthreads_scheduler_parallelism{namespace=~\"${Namespace:.*}\",instance=~\"${instance}\"})"
    }
   ]
  },
  {
   "title": "VT Pool Used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum(vthreads_scheduler_pool_size{namespace=~\"${Namespace:.*}\",instance=~\"${instance}\"}) / sum(vthreads_scheduler_parallelism{namespace=~\"${Namespace:.*}\",instance=~\"${instance}\"})"
    }
   ]
  },
  {
   "title": "Current Mounted VT",
   "type": "stat",
   "description": "Estimate of the number of virtual threads that are currently mounted by the scheduler",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vthreads_scheduler_mounted_virtual_thread_count{namespace=~\"${Namespace:.*}\",instance=~\"${instance}\"})"
    }
   ]
  },
  {
   "title": "Current Virtual Threads Mounted ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(vthreads_scheduler_mounted_virtual_thread_count{namespace=~\"${Namespace:.*}\",instance=~\"${instance}\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Current Queued VT",
   "type": "stat",
   "description": "Estimate of the number of virtual threads that are currently mounted by the scheduler",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vthreads_scheduler_queued_virtual_thread_count{namespace=~\"${Namespace:.*}\",instance=~\"${instance}\"})"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 2, "y": 29 },
     "targets": [
      {}
     ]
    }
   ]
  }
 ]
}