{
 "title": "Helidon Monitoring Dashboard",
 "description": "Helidon Endpoint Metrics Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(instance)" } },
   { "name": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": " base_jvm_uptime_seconds Displays the uptime of the JVM in milliseconds.",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_uptime_seconds{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(requests_count_total{job=\"$job\", instance=\"$instance\"}[5m])",
     "legendFormat": "Requests Per Second"
    }
   ]
  },
  {
   "title": "Thread Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "thread_count{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Thread Count"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "cpu_systemLoadAverage{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "CPU load"
    }
   ]
  },
  {
   "title": "Heap Sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "memory_usedHeap_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Used Heap"
    },
    {
     "expr": "base_memory_committedHeap_bytes{instance=\"$instance\", job=\"$serviceID\", verrazzano_cluster=~\"$vzcluster\", }",
     "legendFormat": "Commited Heap"
    },
    {
     "expr": "base_memory_maxHeap_bytes{instance=\"$instance\", job=\"$serviceID\", verrazzano_cluster=~\"$vzcluster\"}",
     "legendFormat": "Max Heap"
    }
   ]
  },
  {
   "title": "GC Copy & Mark Sweep Total",
   "type": "timeseries",
   "description": "base_gc_total Displays the total number of collections that have occurred. This attribute lists -1 if the collection count is undefined for this collector.",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gc_total{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "GC Copy & Mark Sweep Time",
   "type": "timeseries",
   "description": "base_gc_time_seconds Displays the approximate accumulated collection elapsed time in seconds. This attribute displays -1 if the collection elapsed time is undefined for this collector. The JVM implementation may use a high resolution timer to measure the elapsed time. This attribute may display the same value even if the collection count has been incremented if the collection elapsed time is very short.",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "gc_time_seconds_total{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Access Log",
   "type": "logs",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"$job\", stream=\"accesslog\"} != `metrics`"
    }
   ]
  }
 ]
}